### ISSUE TITLE
Refine the data models for experiment results

### ISSUE THREAD

**Issue by hellais** [ooni/data#42]
We have at the moment a few different approaches to the experiment results data model, yet we don't have one which fits everything nicely.

As part of this task, it would be beneficial to have a bit more clarity on the OONI ontology as it relates to the concepts pertaining to ooni/data.

Below is a slide from my team meeting presentation on the topic which sketches out some of them:
![Screenshot 2023-11-14 at 11 24 09](https://github.com/ooni/data/assets/424620/593683a5-d2c0-4e50-89d3-65fdbbd403f9)

**Comment by bassosimone** [comment]
![image](https://github.com/ooni/data/assets/337298/c988f6d7-f934-4fb4-b33f-aaa719c31fe5)

**Comment by hellais** [comment]
I think a good next step for this would be to document this as part of the new ooni/docs pages.

I am going to make an issue for that.

**Comment by hellais** [comment]
done in ooni/data#54
