### ISSUE TITLE
Evaluate orchestration systems for ooni/data

### ISSUE THREAD

**Issue by hellais** [ooni/data#46]
At the moment OONI/data just runs through crobjob based scheduling.

This is a bit suboptimal because we don't have support for nice logging, retries and monitoring of task execution. It's also not so simple to clearly define task depedencies.

In the past for this use-case we used [airflow](https://airflow.apache.org/) (and even before that [luigi](https://luigi.readthedocs.io/en/stable/)). In the current pipeline we don't use anything, but just rely on systemd because airflow was such a pain to administer and manage.

It looks like the space of orchestration has moved forward quite a bit and there are several nice looking tools in this space at the moment:
* Prefect: https://prefecthq.github.io/prefect-dask/
* Dagster: https://dagster.io/vs
* Mage: https://www.mage.ai/
* Temporal: https://temporal.io/
* flyte: https://flyte.org/

It might be worth spending some time evaluation these options and seeing if it makes sense to use them.

If we pick one of these orchestration tools, given that most of them also support parallelization, we could even get rid of dask and replace it with whatever orchestration tool we choose.

That would simplify the codebase and make monitoring and troubleshooting this in production more robust.

**Comment by ainghazal** [comment]
Not in the same general category as the ones you mention above, but one feature I like from [Toil](https://toil.readthedocs.io/en/latest/running/introduction.html) is the support for a workflow DSL (CWL/WDL) and the ability to run the same jobs locally with minimal overhead (file store) or in a fully-fledged HPC (thinking about reproducibility and supporting research with smaller subsets of the global dataset)

**Comment by hellais** [comment]
I would say we are pretty happy with temporal so we can consider this done.
